name: Finance Spider
on:
  push:
  schedule:
  - cron:  '0 0,2,4,6,8,9,10,11,12,13,14,15,16,17,18,19,20,22 * * *'

jobs:
  spider-xueqiu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Run Spider
      run: |
        python ./xueqiu/spider.py SZ002585 res_result.out
    - name: Cat File
      run: |
        result=$(cat res_result.out)
        echo $result
    - name: Run DataSaver
      run: python ./CI/github/dataSaver.py ${{ secrets.BOT_TOKENS }} res_result.out